### ISSUE TITLE
Указан лишний source в Podfile

### ISSUE THREAD

**Issue by alekoleg** [avito-tech/Paparazzo#1]
В /Example/Podfile указан лишний источник
source 'ssh://git@stash.msk.avito.ru:7999/ma/avito-pod-specs.git'

**Comment by HiveHicks** [comment]
Спасибо, сейчас поправлю

**Comment by HiveHicks** [comment]
Исправлено в 4fe759cfc0e6437fcacff7cf4fa9a9f5453aec8a
