### ISSUE TITLE
Accessing all the images in ImageSource 

### ISSUE THREAD

**Issue by Ahmedshubber** [avito-tech/Paparazzo#15]
@HiveHicks Hello, as I've said before this is a great project. Its the only easily editable photo/camera editing app which I like. But when a user clicks on the media picker to present the paparazzo camera and takes or selects all the photos he or she wants and then clicks the button. on that done button I am passing all 25 images in a segue to another view controller where it will then be accessed in a custom image slider. But I keep getting this error. "Could not cast value of type 'ImageSource.PHAssetImageSource' (0x10e9f17c8) to 'UIImage' (0x110e290b0)." could you please help me. Here is my code. 

Paparazzo view controller: 
<img width="1117" alt="screen shot 2017-03-29 at 8 59 28 pm" src="https://cloud.githubusercontent.com/assets/14989406/24482941/d2c51b46-14c2-11e7-9784-3384206b0712.png">

`@IBAction private func showPhotoLibrary() {
        var theme = PaparazzoUITheme()
        theme.shutterButtonColor = UIColor.blue.cgColor
        theme.shutterButtonDisabledColor = UIColor.black.cgColor
        theme.accessDeniedTitleFont = .boldSystemFont(ofSize: 17)
        theme.accessDeniedMessageFont = .systemFont(ofSize: 17)
        theme.accessDeniedButtonFont = .systemFont(ofSize: 17)
        theme.cameraContinueButtonTitleFont = .systemFont(ofSize: 17)
        theme.cancelRotationTitleFont = .boldSystemFont(ofSize: 14)
        let assemblyFactory = Paparazzo.AssemblyFactory(theme: theme)
        let assembly = assemblyFactory.photoLibraryAssembly()
        
        let galleryController = assembly.module(
            selectedItems: [],
            maxSelectedItemsCount: 5,
            configuration: { [weak self] module in
                weak var module = module
                module?.onFinish = { result in
                    
                    if case let .selectedItems(photoLibraryItems) = result {
                        self?.photos = photoLibraryItems.map { $0.image }
                        self?.updateUI()
                        self?.performSegue(withIdentifier: "ShowNow", sender: self?.photos)
                    }
                }
            }
        )
        
        let navigationController = UINavigationController(rootViewController: galleryController)
        
        present(navigationController, animated: true, completion: nil)
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if (segue.identifier == "ShowNow") {
            let pivc: view2ViewController? = segue.destination as? view2ViewController
            
            pivc?.arrImages = photos
            // here images is the array of images
            
        }
    }`

Photo slider view controller:
<img width="1107" alt="screen shot 2017-03-29 at 8 59 20 pm" src="https://cloud.githubusercontent.com/assets/14989406/24482942/d2c5085e-14c2-11e7-9230-9e853dc72f0e.png">

`@IBOutlet weak var imgSlider: UIView!
  var passedPhotos: [ImageSource]?
  var arrImages =  Array<Any>()
  fileprivate var sliderVc1: LIHSliderViewController!

  override func viewDidLoad() {
    super.viewDidLoad()
    let slider1: LIHSlider = LIHSlider(images: arrImages as! [UIImage]) I'm getting this error  "Could not cast value of type 'ImageSource.PHAssetImageSource' (0x10e9f17c8) to 'UIImage' (0x110e290b0)." right here. Its a thread break error. So if you can show me how I can access all the images from the paparazzo view controller, I'd really appreciate it. Thanks 
`

**Comment by HiveHicks** [comment]
You cannot cast `ImageSource` to `UIImage`. Use `ImageSource`'s `requestImage` method to get `UIImage` instance. Also see https://github.com/avito-tech/Paparazzo/tree/develop#ImageSource for more info on how to treat `ImageSource` in common use cases.

**Comment by jackpaster** [comment]
@HiveHicks can you please sh me how I can cast type imagesource request method because I don't see that in the documentation and that's what I'm confused about.

**Comment by HiveHicks** [comment]
@jackpaster you should specify image type in `resultHandler` parameters list:

```swift
imageSource.requestImage(options: options) { (result: ImageRequestResult<UIImage>) in
    // ...
}
```

**Comment by jackpaster** [comment]
@HiveHicks and lastly could you show me how I would access all the images inside the function you have above. Thanks for your help.

**Comment by Ahmedshubber** [comment]
Hello, thanks again but I stayed up at my computer for three hours trying
to implement the function you showed me yesturday and it wasn't
registering. With the code I showed you in view controller 2. Could you
show me how I could access the images with the function so that the images
from the camera are in my custom image slider. I've spent hours trying to
fix this and I'm still stressing over this. Could you please show me in my
code in an edit on how I could fix this. I created a stackoverflow before
like you asked and never got an answer from you so I just created another
issue. Please I need to resolve this so that I can update my app and tell
my users that I'm using paparazzo camera in my app now.
