### ISSUE TITLE
MVC version?

### ISSUE THREAD

**Issue by ronysteel** [avito-tech/Paparazzo#19]
Hi, any plans for MVC version? The VIPER is great but to I can't understand the implementation :)

**Comment by HiveHicks** [comment]
@ronysteel, the architecture of Paparazzo doesn't impose restrictions on the architecture of your own app. It will fit in MVC, MVVM, MVP and anything else you can think of. However, if you want to be a contributor, you'll have to stick to VIPER — we won't provide MVC implementation.

**Comment by ronysteel** [comment]
@HiveHicks nice answer :)
