### ISSUE TITLE
Is It possible to edit image from photo library?

### ISSUE THREAD

**Issue by chapayGhub** [avito-tech/Paparazzo#26]
I want to choose image from photo library and edit it(crop, rotate etc)
Is it possible?
If yes how?

**Comment by HiveHicks** [comment]
It is possible.

1. Open Paparazzo and tap camera icon.
2. At the bottom left corner you'll see a preview of the last photo in your photo library. Tap it.
3. Pick photos from the library and tap Done.
4. Select a photo that you want to edit in Paparazzo and tap Edit button which is located in the bottom right corner.

![simulator screen shot 2 d0 bc d0 b0 d1 8f 2017 d0 b3 2c 17 35 53](https://cloud.githubusercontent.com/assets/1489247/25623935/af78c6d4-2f60-11e7-8163-432d5bac4a33.png)

**Comment by chapayGhub** [comment]
Thanks!
I found this by self ;)
Is it possible to use crop functionality from "photoLibraryAssembly" ui component?

**Comment by HiveHicks** [comment]
Could you please clarify what exactly you need? Do you want to use cropping screen without everything else?

**Comment by HiveHicks** [comment]
Closed due to inactivity. Feel free to reopen if needed.
