### ISSUE TITLE
Saving images to server and extracting them

### ISSUE THREAD

**Issue by Ahmedshubber** [avito-tech/Paparazzo#38]
@prn @limarc @eshkinkot @dkostyrev @lahmatiy Hey guys, I love this project its great. I just have one problem. once I extract my images from my server and want to edit the images or change the images I have using the paparazzo camera, Do I convert all my images back and put them into an image source array and set it in items down below or what do I do. Thanks again.

**Comment by Ahmedshubber** [comment]
if you need more clarification to my first question i could post my code for you

**Comment by Ahmedshubber** [comment]
@prn @limarc @eshkinkot @dkostyrev @lahmatiy is there a way to convert an array of images into an image source array. Please let me know.

**Comment by dkostyrev** [comment]
@Ahmedshubber can you please stop tagging random people in your issues?

**Comment by Ahmedshubber** [comment]
No problem, do you have a suggestion to fix this issue.

**Comment by Ahmedshubber** [comment]
@HiveHicks I really need your help right now. Ive tried to solve this problem for weeks now but have no solution. How can I preload an array of images in the mediapickerViewController. Can I please have a response. It's something thats not documented on this repository.

**Comment by HiveHicks** [comment]
> It's something thats not documented on this repository.

The example project actually **contains** exactly what you want. You use `RemoteImageSource` to create `ImageSource` for a remote image (using it's url). Be sure to reference `ImageSource/Remote` and one of `ImageSource/AlamofireImage or `ImageSource/SDWebImage` depending of the library you prefer for network communication.

Creating `RemoteImageSource` is easy:

`let imageSource = RemoteImageSource(url: "http://www.velvet.by/files/userfiles/19083/ekrk.jpg")`

**Comment by Ahmedshubber** [comment]
@hivehicks thanks for responding. But I already tried that l. I want to to know how you can create an imagesource from images stored locally and not through a URL. After that where do I place the imagesource in the mediapicker function. Do I place imagesource in the items category. Cheers.

**Comment by HiveHicks** [comment]
```swift
let paths: [String] = ...

let items = paths.map { path in
    MediaPickerItem(image: LocalImageSource(path: url), source: .camera)
}

let factory = Paparazzo.AssemblyFactory()
let assembly = factory.mediaPickerAssembly()

let viewController = assembly.module(
    items: items,
    ...
```

**Comment by Ahmedshubber** [comment]
@HiveHicks one last question for paths. What do I use strings for in the array set for paths. I'm not using a URL. I using a local uiimages from my assets

**Comment by HiveHicks** [comment]
Save them to disk and use those paths. You shouldn't store many `UIImages` in memory. It will inevitably lead to a crash due to memory warning.

**Comment by Ahmedshubber** [comment]
@HiveHicks ok I'll try and message you if any warnings come up

**Comment by Ahmedshubber** [comment]
@HiveHicks One last thing. This keeps coming up. I'm trying to append data to an array from the full resolutionimage function provided in the documentation. But the swift element comes up nil once its declared outside the function. Can you please answer me on this because i can't access the data and do things with it outside the function Here is my example. 

> var photos2: [ImageSource]?
                var files : [Data] = []
                let _ = self.photos2?.map { path in
                    path.fullResolutionImageData{ data in
                        files.append(data) --> (prints 2)
                    }
                }

**Comment by Usipov** [comment]
@Ahmedshubber, the`fullResolutionImageData` is an asyncronous method. 
I guess `files.append(data)` gets exectued after `print("(files.count)")`

**Comment by HiveHicks** [comment]
@Usipov is right. Morover, you shouldn't keep array of Data in memory. The reason, as I already said, is that your app will inevitably crash due to memory warning.

**Comment by Ahmedshubber** [comment]
@hivehicks there's no memory issue because after 69 sec the data will disappear. It doesn't stay in memory. But is there a way around this asyncroneas method to access the data outside the function so I can do other stuff with it.

**Comment by Ahmedshubber** [comment]
@hivehicks @usipov Forget memory right now because I did unit testing and I can gaurentee you I won't have a memory crash. I just need to access all the data files outside this function. Do you know a workaround.

**Comment by HiveHicks** [comment]
Launch your app in iPhone 4 and I guarantee that you **will** face memory issues.

We are happy to help you if you have problems with our library. However, what you're asking is a general programming question. I suggest you to take programming courses or to use StackOverflow for such kind of questions.
