### ISSUE TITLE
Main.Storyboard

### ISSUE THREAD

**Issue by Ahmedshubber** [avito-tech/Paparazzo#4]
@prn @limarc @eshkinkot @dkostyrev @lahmatiy  First of all, this project is the best camera project I've personally seen on github by far. But theres one thing thats got me confused and frustrated. So I have a construction app that takes pictures of construction sites. At the end of filling out the information, a user will click on the button to present the camera view Is there anyway you guys could make an example implementing this project with a uistoryboard.

**Comment by HiveHicks** [comment]
Hi, @Ahmedshubber. Thanks for giving Paparazzo a try!
I've just pushed an example of using Paparazzo with storyboard to develop. Build and run `PaparazzoExample_Storyboard` target to see it in action.

**Comment by Ahmedshubber** [comment]
@HiveHicks @prn @limarc @eshkinkot @dkostyrev Sorry but I'm not finding PaparazzoExample_Storyboard target In your project. I only find this NoMarshroute and PaparazzoExample
