### ISSUE TITLE
Add iPhone X support

### ISSUE THREAD

**Issue by HiveHicks** [avito-tech/Paparazzo#48]

**Comment by jackpaster** [comment]
@HiveHicks hello, I opened the same issue and you told me you would have the project fully functional with iPhone X. There’s still a lot of issues that need to be issues with the design. When are you positive you will have it all done. I just need to know when so I can release my app.

**Comment by HiveHicks** [comment]
@jackpaster sorry to keep your waiting, it was a busy week for me. There are still a few issues with iPhone X, but most of the work is done. Use `develop` branch to stay up-to-date until we release 2.1.0.

**Comment by jackpaster** [comment]
The size of each image in the picker when your scrolling through the images you can edit in the slider are massive. And there’s a bug when you click the photo library button for the first time the cancel and done buttons don’t layout. Do you think you can have the look and these small things that make a big difference done this week. I’m really overdue for release that’s why I’m asking.

**Comment by jackpaster** [comment]
@HiveHicks when will 2.1.0 be released. Is there a timeline

**Comment by HiveHicks** [comment]
> The size of each image in the picker when your scrolling through the images you can edit in the slider are massive. And there’s a bug when you click the photo library button for the first time the cancel and done buttons don’t layout

As I already said, you need to use `develop` branch. These bugs have already been fixed there.

In your Podfile:

```
pod 'Paparazzo', :git => 'https://github.com/avito-tech/Paparazzo', :branch => 'develop'
```

**Comment by HiveHicks** [comment]
That's how Paparazzo looks like on iPhone X in `develop`

<img width="400" alt="2017-11-21 16 03 40" src="https://user-images.githubusercontent.com/1489247/33073982-9f7e6a6c-ced5-11e7-9d73-2c808e42c6cf.png">
<img width="400" alt="2017-11-21 16 03 58" src="https://user-images.githubusercontent.com/1489247/33073983-9f98a67a-ced5-11e7-963e-9c62dcd59535.png">

**Comment by jackpaster** [comment]
@HiveHicks you said there are still a few issues that need to be fixed. If it looks good like you said. What are the few issues that need to be fixed for the iPhone X. And when do you expect to complete them all. Thanks

**Comment by HiveHicks** [comment]
@jackpaster everything should be fixed now in `develop` branch. If you find any issues, feel free to post it here.

**Comment by jackpaster** [comment]
@HiveHicks Yes I found one. When I click on photo library the view is hidden underneath the small cutout for the top bar on the new iPhone x. But everything else works nicely. can you take a look. Heres an image. It looks good from the picture you showed but when I run paparazzo camera on a normal navigation controller it doesn't work. Can you please explain. 
<img width="381" alt="screen shot 2017-11-26 at 7 03 48 pm" src="https://user-images.githubusercontent.com/17861785/33245932-90c4b5f2-d2dc-11e7-837d-ae5b7b5dca62.png">

**Comment by jackpaster** [comment]
@HiveHicks It seems as though the status bar is hidden

**Comment by jackpaster** [comment]
@HiveHicks Two questions. Can you merge the new design for the photo library with the develop branch and make it one whole branch, and can you make the new photo library design iPhone x compatible. What is the timeline for these two requests do you think

**Comment by jackpaster** [comment]
@HiveHicks What do you think

**Comment by HiveHicks** [comment]
This feature is being tested at the moment. We will merge it into develop as soon as it's approved by our QA specialists. Hopefully this week, but I can't tell you the exact date.

**Comment by jackpaster** [comment]
@HiveHicks thanks its a great update. I love the updated design so much so I hope you guys get it in really soon
