### ISSUE TITLE
pod install

### ISSUE THREAD

**Issue by jackpaster** [avito-tech/Paparazzo#56]
@HiveHicks I'm trying to install the pods for the updated project but all im getting is the files from the old version. I did pod 'Paparazzo' and my minimum deployment target is iOS 9. What do you think could be the problem

**Comment by jackpaster** [comment]
@HiveHicks could you update the pods for this project. I think that is the problem

**Comment by HiveHicks** [comment]
What version do you want to install?

**Comment by jackpaster** [comment]
@HiveHicks the latest one with all the updates. When I download the project off current project off GitHub. Thats the one I want

**Comment by jackpaster** [comment]
@HiveHicks But when I go into the pod file and run the 2.0.0 pod, it gives me the old version

**Comment by jackpaster** [comment]
@HiveHicks the current version on GitHub that was updated 15 days ago is the pod I want. I want the current most version of paparazzo but in a pod

**Comment by HiveHicks** [comment]
We haven't released a new version yet, but you can get all the latest features of Paparazzo by using the version that's in `develop` branch. To do that you need to specify in your `Podfile`:

```
pod 'Paparazzo', :git => 'https://github.com/avito-tech/Paparazzo.git', :branch => 'develop'
pod 'ImageSource', :git => 'https://github.com/avito-tech/Paparazzo.git', :branch => 'develop'
```
