### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by mak21** [avito-tech/Paparazzo#59]
Thanks for the awesome framework please can you update it to Swift 4 to support new apps built in swift 4.
Keep Up the good work

**Comment by HiveHicks** [comment]
These shouldn't be any issues with integrating Paparazzo in Swift 4 app as long as Swift 3.2 and 4.0 can exist in a single project. The latest version of Cocoapods supports that.

**Comment by DogandElk** [comment]
I added the dependency by adding it through Cocoapods and when I tried to run the app I received all kinds of errors stating that the code had been deprecated plus there is an error in the task that makes the app crash.  What a waste of time.  I am in Xcode 9.2 Swift 4

**Comment by HiveHicks** [comment]
@DogandElk what version of Cocoapods are you using?

**Comment by DogandElk** [comment]
How do I determine that ?

**Comment by DogandElk** [comment]
Version 1.3.1

**Comment by voluntas88-xsolve** [comment]
I set Swift Language Version to 3.2 for Paparazzo in Build Settings and it helped me with compile errors. Also it should be done after every `pod update`.

**Comment by HiveHicks** [comment]
I've migrated Paparazzo to Swift 4 in swift-4 branch and found the reason for empty camera view. It will soon be merged into develop.

**Comment by DogandElk** [comment]
That sounds Great !  I'll be looking forward to hearing from you when it is ready .

Happy New Year !

Tom

**Comment by DogandElk** [comment]
Happy New Year !

We are wondering when you will post the updated changes so we can update our pod file ?

**Comment by HiveHicks** [comment]
@DogandElk I'm on vacation right not, so the pull request with this migration is expected to be merged only on January 9th or so. Meanwhile you can use `swift-4` branch of the pod in your Podfile.

**Comment by DogandElk** [comment]
Hi,

Any word on the update ?

**Comment by HiveHicks** [comment]
Swift 4 support is merged into `develop`

**Comment by rjjohnpatrickcruz** [comment]
This library is awesome, I just want to know updates in swift 4 conversion. Thank you!
Cheers!

**Comment by bystritskiy** [comment]
@HiveHicks Hi! When will the release? Thank you

**Comment by HiveHicks** [comment]
@rjjohnpatrickcruz @bystritskiy you can use the latest development version if you need Swift 4 support. It's production ready.

To do that you need to specify in your Podfile:

`pod 'Paparazzo', :git => 'https://github.com/avito-tech/Paparazzo', :branch => 'develop'`

You can treat this as Paparazzo 3.0 beta. We still need to complete some tasks in order to publish the final version in Cocoapods repo.

**Comment by fabiojgrocha** [comment]
@HiveHicks it would have to be: 
`  pod 'ImageSource', :git => 'https://github.com/avito-tech/Paparazzo', :branch => 'develop'
  pod 'Paparazzo/Core', :git => 'https://github.com/avito-tech/Paparazzo', :branch => 'develop'`
