### ISSUE TITLE
The passing images

### ISSUE THREAD

**Issue by jackpaster** [avito-tech/Paparazzo#6]
@prn @limarc @eshkinkot @dkostyrev @lahmatiy thanks for helping me out last type with the storyboard example but two more questions. Is there anyway to access the images taken by the camera because I plan on passing them to a new view controller

**Comment by lahmatiy** [comment]
@jackpaster Please, don't mention random persons in your comments. Some of them (like me) doesn't relate to this project. More over maintainers and watchers recieve notifications even without mentioning. Thank you.

**Comment by HiveHicks** [comment]
@jackpaster You can set module's `onFinish` closure in module configuration block. This closure has a parameter which is an array of selected `MediaPickerItem`s. You can see the example in https://github.com/avito-tech/Paparazzo/blob/master/Example/PaparazzoExample/Example/Presenter/ExamplePresenter.swift (lines 53-56):

```
module.onFinish = { [weak module] items in
    debugPrint("media picker did finish with \(items.count) items:")
    items.forEach { debugPrint($0) }
    self?.items = items
    ...
```

Thanks for pointing this out. I'll fix the documentation soon.

**Comment by jackpaster** [comment]
Sorry

**Comment by jackpaster** [comment]
@HiveHicks now I want to have three of these cameras in three dofferent storyboards. Do I have to have three different examplepresenter view controller. One for each camera. And if so, what other view controllers need to be multiplied for each individual camera

**Comment by HiveHicks** [comment]
@jackpaster First of all, you don't have to use Presenter at all. `PaparazzoExample` is written using VIPER architecture, that's why it has Presenter, Router, Interactor and other stuff. You don't need all that. You just need to create Paparazzo's view controller like you create any other view controller programmatically. The only difference is that you don't create it with typical `UIViewController`'s initializer, but rather using `AssemblyFactory`:

```
let factory = Paparazzo.AssemblyFactory()
let assembly = factory.mediaPickerAssembly()

let viewController = assembly.module(
    items: items,
    selectedItem: selectedItem,
    maxItemsCount: maxItemsCount,
    cropEnabled: true,
    cropCanvasSize: cropCanvasSize,
    configuration: { module in
        module.onFinish = { [weak module] photos in
            // do whatever you want with photos
            module?.dismissModule()
        }
        module.onCancel = { [weak module] in
            module?.dismissModule()
        }
    }
)
```

Perhaps we would add some component to simplify using Paparazzo from storyboard so that you don't have to write any code. I'll do a research.

**Comment by jackpaster** [comment]
I'm having a hard time just using This without viper architecture. Could
you possible edit the existing storyboard project to work from a regular
uiviewcontroller without viper architecture. Thank you.

**Comment by jackpaster** [comment]
@HiveHicks i have a contraction app and at the end after filling in all the information A user will click a button and take pictures of the construction site and then when they finish there will be a preview where the user can view all the images and scroll threw them and view the information they filled in before. I've done this all in storyboards and this project is great for that. That's why I asked you to use storyboards. But I think it will be hard to implement with viper arcticeture. So if you could show me how to implement it all with one view controller in one storyboard without presenters, etc. I would really appreciate it. Thanks for all your help

**Comment by jackpaster** [comment]
What do you think

**Comment by HiveHicks** [comment]
@jackpaster I will have time for that in an hour or two. I'll let you know when it' ready.

**Comment by jackpaster** [comment]
Thank you

**Comment by HiveHicks** [comment]
@jackpaster I've slightly modified an example. Now it displays the first photo picked via Paparazzo in image view of `ViewController` that presents it. If you need to display an array of `ImageSource` in collection view, there's `UIImageSourceCollectionViewCell` that you can use for that. More info on `ImageSource` is coming (#3).

**Comment by jackpaster** [comment]
@HiveHicks what do you think

**Comment by HiveHicks** [comment]
@Ahmedshubber I'm not sure what you're trying to do with photos. I recently added documentation section about `ImageSource` [here](https://github.com/avito-tech/Paparazzo/tree/develop#ImageSource). It should help.

**Comment by jackpaster** [comment]
@HiveHicks after I've taken and edited all the images. I want to go to a preview view controller or another view controller with an image slider. I already have the slider and how I get the images from the camera view controller to the preview or next view controller is to pass the images through a segue. No in order to pass the images. I have to access all uiimages from imagesource. I get a crash if I declare to pass imagesource because image source is an array. What is the code to access all uiimages from the imagesource. You showed me how to access the first image as photos.first. Is there something like photos.all where I can access all uiimages from imagesource. That's what I'm trying to accomplish.

**Comment by jackpaster** [comment]
@HiveHicks you say the easiest method is to access the first parameter in image source. How can I access all parameters in imagesource

**Comment by jackpaster** [comment]
What do you think

**Comment by jackpaster** [comment]
@HiveHicks I'll pay you 10$ if you can help me on upwork

**Comment by jackpaster** [comment]
I won't use PayPal because of the transaction fees

**Comment by HiveHicks** [comment]
> You showed me how to access the first image as photos.first. Is there something like photos.all

You can iterate an array using `forEach` function: https://developer.apple.com/reference/swift/array/1689783-foreach

**Comment by Ahmedshubber** [comment]
Can you help me if I pay you

**Comment by artyom-razinov** [comment]
Guys, we don't offer programming courses. If you can't figure out how to solve these problems by yourself (I hope you are not banned on google), you choose wrong profession.

**Comment by etolstoy** [comment]
@jackpaster @Ahmedshubber Thanks for your interest in our project! We're happy that Paparazzo helps you.

However, we use GitHub Issues only for tracking bugs and enhancements. If you have any general programming questions - feel free to ask them on [StackOverflow](http://stackoverflow.com/). If you'll have any questions about Paparazzo - add a corresponding tag in your question and we'll try to answer it (for free, we don't take money for our open source projects).
