### ISSUE TITLE
Camera View is not appearing !

### ISSUE THREAD

**Issue by skander300** [avito-tech/Paparazzo#62]
I am using code snippets from storyboard example.
Everything works fine except for camera view that is showing nothing(but a white background).
The strange thing , that i take can take pictures. 
PS : Swift 4 , iOS 11 and i converted Paparazzo pod to swift 4
Any help ?

**Comment by HiveHicks** [comment]
@skander300 Perhaps you've done something wrong converting pod to Swift 4, and that causes the problem. Why did you ever need to to that. You can perfectly use pods written with older versions of Swift in the app that's written in Swift 4. We're using it that way.

**Comment by skander300** [comment]
I already tried that, but a crash occurs whenever i press on "Done" button

**Comment by HiveHicks** [comment]
Can you attach the crashlog?

**Comment by skander300** [comment]
apparently i wasn't managing well my navigation controller that was pointing to nil view controllers.
But i have a suggestion : 
what if i change presenting camera view controller from 

> navigationController?.pushViewController(mediaPickerController, animated: true)
To

> self.present(mediaPickerController, animated: true, completion: nil)

and change func dismissCurrentModule(animated: Bool) in BasicUIKitRouter.swift to this

> func dismissCurrentModule(animated: Bool) {
> guard let viewController = viewController else { return }
>       viewController.dismiss(animated: animated, completion: nil)
> }

i remarked that this way, uou wouldn't have to worry about your navigation controller managing well your views, what do you say about this ?

**Comment by HiveHicks** [comment]
@skander300 I assume that by creating #63 you mean that Camera View **did** appear. Correct me if I'm wrong.

**Comment by skander300** [comment]
@HiveHicks yes camera did appear when i left pod with swift 3.2
but whenever i convert to swift 4, camera won't appear.

**Comment by HiveHicks** [comment]
Well, I guess the solution is obvious — just don't convert it to Swift 4 :) We'll do it ourselves someday.

What about the crash? Are you still experiencing it?

**Comment by skander300** [comment]
I would be great if you convert it to swift 4 since it's the only solution that prevents my app from crashing.
I tried to do it by myself but camera view does not appear anymore and i could no longer take pictures after selecting photos from gallery.
Any way , this pod is great, keep up the good work :)

**Comment by HiveHicks** [comment]
Please attach the crash log so that we could help you with the crash.

**Comment by HiveHicks** [comment]
I've migrated Paparazzo to Swift 4 in `swift-4` branch and found the reason for empty camera view. It will soon be merged into `develop`.
