### ISSUE TITLE
Generic T could not be inferred

### ISSUE THREAD

**Issue by jackpaster** [avito-tech/Paparazzo#65]
@prn @eshkinkot @dkostyrev @pkorobeinikov @lahmatiy  Im trying to get an image using your fullresolutionimage function, but I keep getting an error called Generic Paramerter T could not be inferred. Here is my code. All I want to do is get a uiimage from an array. I don't want to set the image I just want to get it for the i or path of an array. But im having Alot of issues. I love this library but I can't use it if I can't access the images properly. Because getting the image data and converting it to a uiimage and then converting it to a jpeg to save it nicely to my server is taking forever. Im talking 5 min to save 5 images. And that why I need a function to just get the uiimage directly. 

> var photos2: [ImageSource]?
self.photos2?.forEach{ path in
                    myGroup.enter()
                    path.fullResolutionImage({ (image) in              
        })
  }

**Comment by HiveHicks** [comment]
You need to specify the type of image you want to get in parameters:

```
path.fullResolutionImage { (image: UIImage?) in
    // ...
}
```

P.S. Please stop mentioning random people when creating issues.
