### ISSUE TITLE
Problem with building project

### ISSUE THREAD

**Issue by vkaltyrin** [avito-tech/Paparazzo#66]
I added paparazzo to the podfile, then did 'pod install', tried to build the project and received error:

![2018-03-28 13 44 53](https://user-images.githubusercontent.com/3104552/38024690-68869800-328e-11e8-85a1-576af1a43149.png)

FYI

Maybe I will make a PR to fix the issue if I have time.

**Comment by khomTima** [comment]
Thanks for the comment, we'll fix it soon.
