### ISSUE TITLE
How to get name of selected image

### ISSUE THREAD

**Issue by bhushanishere** [avito-tech/Paparazzo#70]
Hi,
I need selected image name so how can i get image name? Please help me.

Thanks in advance... :)

**Comment by HiveHicks** [comment]
Hello. What do you mean by name? And why do you need it for?

**Comment by HiveHicks** [comment]
ImageSource doesn't have a name. If you tell me why do you need it for, maybe I would offer you a solution.

**Comment by bhushanishere** [comment]
Thanks for replying. 
I need filename for user prospective only.

**Comment by HiveHicks** [comment]
`ImageSource` is an image abstraction, and image may not be backed by a file, hence there is no filename property.
