### ISSUE TITLE
Crop isn't working

### ISSUE THREAD

**Issue by ghertyish** [avito-tech/Paparazzo#72]
This pod is awesome but the crop doesn't seem to be working for me. When I click on the crop icon nothing happens on screen and I get this log:

`2018-06-17 02:46:43.291844+0100 AppName[2095:993923] [ImageManager] Unable to load image data, /var/mobile/Media/DCIM/100APPLE/IMG_0841.JPG`

Does anyone know why this is coming up?

**Comment by HiveHicks** [comment]
Hello @ghertyish! Can you please provide more info about the device you're using and iOS version?

**Comment by ghertyish** [comment]
Hi! I've tried it on multiple simulators using iOS 11.4 and on my iPhone 6s, again using iOS 11.4. Your question made me wonder so I downloaded iOS 10.3.1 simulators but it doesn't seem to be working on them either. 

I should have noticed before but the log I printed above only seems to come up on my iPhone and not any of the simulators. The simulators don't have any console log, the crop button just doesn't do anything.

**Comment by ghertyish** [comment]
I should also mention that I'm using the develop branch, although I just tried using the master branch and it still doesn't seem to be working for me.

**Comment by HiveHicks** [comment]
Using `develop` branch is perfectly okay and should work.

Does the problem take place with each of your photos? You're picking them from your Photo Library, right?

The log message itself seems to be a bug of iOS 11, as described here: https://stackoverflow.com/questions/46377824/ios-11-imagemanager-unable-to-load-image-data. But you should be able to proceed to cropping anyway. Strangely, it's not happening for you. Can you please record a video, maybe it will give me some ideas about the source of the problem.

**Comment by ghertyish** [comment]
Yes, the problem seems to be with all photos. The log I printed above only seems to be coming up on photos from the photo library on my phone however. It doesn't show up on photos that have just been taken on the camera. 

I also seem to be getting the log below occasionally from the simulator but I haven't noticed it on the iPhone. It comes up when selecting the images from the library; not when clicking crop.

`2018-06-17 02:46:43.291844+0100 AppName[2095:993923] [Generic] Creating an image format with an unknown type is an error`

I've uploaded a video here: [https://streamable.com/h5gtc](url)

**Comment by HiveHicks** [comment]
@ghertyish I'm assuming that you're not presenting Paparazzo inside a navigation controller, which is required for crop to work. See the following snippet from `PaparazzoExample_NoMarshroute` project:

```swift
let viewController = PaparazzoFacade.paparazzoViewController(
    theme: PaparazzoUITheme.appSpecificTheme(),
    parameters: MediaPickerData(
        items: mediaPickerItems,
        maxItemsCount: 3
    ),
    onFinish: { images in
        mediaPickerItems = images
    }
)

exampleController?.present(viewController, animated: true)
```

`PaparazzoFacade.paparazzoViewController` actually returns a `UINavigationController` instance with Paparazzo view controller as the root view controller.

Please let me know if it helps.

**Comment by ghertyish** [comment]
Ah, I must have been looking at the wrong example. That's fixed it now. 
I'm really happy it's working, the media picker looks really good.

Thank you for all your help, I really appreciate it.

**Comment by HiveHicks** [comment]
You're welcome! :)
