### ISSUE TITLE
Fatal error: Not enough bits to represent the passed value

### ISSUE THREAD

**Issue by Umity** [avito-tech/Paparazzo#74]
When i am cropping a photo and tap to the check/OK button then i get this error
Fatal error: Not enough bits to represent the passed value

    public init<T: Hashable>(hashable: T) {
        self.init(int32Value: Int32(hashable.hashValue))
    }

ImageRequestId.swift

**Comment by InViZz** [comment]
same issue

**Comment by bystritskiy** [comment]
same +

**Comment by shireeshMs** [comment]
the same issue on Xcode 10 iOS 12

**Comment by HiveHicks** [comment]
@shireeshMs can you please check what version of `ImageSource` is specified in your Podfile.lock? Is it 2.1.0?

**Comment by HiveHicks** [comment]
Oh, sorry, I confused it with another problem

**Comment by shireeshMs** [comment]
![screenshot 2019-01-10 at 5 01 56 pm](https://user-images.githubusercontent.com/37240061/50965960-89092180-14f9-11e9-941b-6c4fd530f263.png)
and yes it is 2.1.0 @HiveHicks 
still if you have something for this issue please let me know

**Comment by HiveHicks** [comment]
The issue should be resolved now by https://github.com/avito-tech/ImageSource/commit/a9ce17b95d1aa4b7ecf0bbda9660f19b3702c38f
ImageSource 2.2.1 is now used in develop branch of Paparazzo.

**Comment by HiveHicks** [comment]
And now it's in master, followed by the release of Paparazzo 3.0.0
