### ISSUE TITLE
Change Camera!

### ISSUE THREAD

**Issue by smahdi** [avito-tech/Paparazzo#76]
How I can change Camera lib to another?
like [WeScan](https://github.com/WeTransfer/WeScan)
Tanks.

**Comment by smahdi** [comment]
Or add( two camera library)!?

**Comment by HiveHicks** [comment]
You should look for instructions on how to integrate another library into your app in it's own documentation.

**Comment by HiveHicks** [comment]
If that's not what you were asking about, feel free to reopen the issue.
