### ISSUE TITLE
Add support to Swift 4.2

### ISSUE THREAD

**Issue by bystritskiy** [avito-tech/Paparazzo#77]

**Comment by HiveHicks** [comment]
Thanks for the report. I'm planning to do that by the end of the week.

**Comment by HiveHicks** [comment]
@bystritskiy, check out `swift-4.2` branch. You will need to use `ImageSource` from the branch with the same name by specifying it in your Podfile.
```
pod 'Paparazzo', :git => 'https://github.com/avito-tech/Paparazzo', :branch => 'swift-4.2'
pod 'ImageSource', :git => 'https://github.com/avito-tech/ImageSource', :branch => 'swift-4.2'
```

**Comment by HiveHicks** [comment]
We're moving forward to  #81 :)
