### ISSUE TITLE
Random camera freezes & lags

### ISSUE THREAD

**Issue by bystritskiy** [avito-tech/Paparazzo#80]
Good day!

When I using the paparazzo controller found such a problem.
**When opening of the paparazzo camera, camera has terrible lags and freezes.**

I can not find the pattern and thought, maybe I did something wrong, and there is a memory leak and loss of resources phone.

**But, I discovered a strange pattern**
This bug only occurs when _maxItemsCount = 1_ (But sometimes everything is okay)

I checked example from the repository. I also got this bug

Recorded a little video for more understanding:
https://www.youtube.com/watch?v=O7IhHAdLxDw

**Comment by bystritskiy** [comment]
I caught this bug in main Avito app :(

**Comment by HiveHicks** [comment]
@bystritskiy sorry it took so long. This should be fixed in 275ae2e999f78c4fb6dda240cdab0de4f67ebb35
