### ISSUE TITLE
How can selected photos be uploaded on server?

### ISSUE THREAD

**Issue by ac1dpax** [avito-tech/Paparazzo#85]
I am trying to upload photos on server using Alamofire like this without success:

```
Alamofire.upload(multipartFormData: { multipartFormData in
       for photo in self.photos{
        photo.fullResolutionImageData() { data in
            multipartFormData.append(data!, withName: "uploaded_file", fileName: "\(Date().timeIntervalSince1970).jpeg", mimeType: "image/jpeg")
           }
       }
```

getting error 200: esponseSerializationFailureReason.inputDataNilOrZeroLength

**Comment by HiveHicks** [comment]
Hello. `fullResolutionImageData` is asynchronous, so in your code multipart data won't be appended inside the loop. And I suppose `Alamofire.upload(multipartFormData:` expects it.
