### ISSUE TITLE
Xcode 12, iOS 14 PHPhotoLibrary.authorizationStatus

### ISSUE THREAD

**Issue by alxarsnk** [avito-tech/Paparazzo#87]
PHPhotoLibrary.authorizationStatus

new Field
<img width="1804" alt="Снимок экрана 2020-09-17 в 12 39 58" src="https://user-images.githubusercontent.com/32188461/93453876-e6669000-f8e2-11ea-9d4c-000e72a1a3ff.png">

PhotoLibraryItemsService.swift
line 153
Switch must be exhaustive

**Comment by HiveHicks** [comment]
Thanks for the report. I'm going to resolve this hopefully next week.

**Comment by HiveHicks** [comment]
The fix is now in branch SEL-12575-ios14

**Comment by HiveHicks** [comment]
Merged to master, included in 5.0.0 release
