### ISSUE TITLE
Can't update to version 5.0.0

### ISSUE THREAD

**Issue by ac1dpax** [avito-tech/Paparazzo#88]
Tried to update to version 5.0.0 using CocoaPods without Marshroute: pod "Paparazzo/Core" without success.

**Comment by HiveHicks** [comment]
Hi. What error are you getting?

**Comment by ac1dpax** [comment]
No errors, if I do pod install it just install 4.0.0 version, on pod update it doesn't update it to 5.0.0

**Comment by HiveHicks** [comment]
Try running `pod repo update`, then `pod update Paparazzo ImageSource`. Also check that version 4.0.0 is not specified explicitly in your Podfile.

**Comment by ac1dpax** [comment]
Worked! Thank you!
